### ISSUE TITLE
Document steps for building and configuring manually

### ISSUE THREAD

**Issue by rushmorem** [betweenlines/intecture-auth#8]
[The book](https://intecture.io/book/rust/ch01-02-intro-installation.html) mentions that you can compile from source using `make`. This is great. However, it would even be better if we also have instructions on how to build and configure manually without using the `Makefile`. Specifically, mention:-

* `cargo build --release`,
* and how to setup `/etc/intecture`

so commands like `inauth_cli user add <username>` can just work out of the out of the box.

**Comment by itpetey** [comment]
Agreed. I got lazy on that one! I'll add it to the list.

**Comment by itpetey** [comment]
This is now covered in the reference section of the book. For example, here's the Auth install guide: https://intecture.io/book/rust/ch05-03-01-reference-auth-installation.html
